### ISSUE TITLE
Can this solver solve the opening position?

### ISSUE THREAD

**Issue by tadpoleloop** [lhorrell99/4-in-a-Robot#1]
I've made a fair share of implementations of solvers for various games, and I remember I could never get a python implementation to solve the game in a reasonable amount of time.

But when I compiled the same python code to a Cython project I could solve it in seconds. I was wondering how this solver performs.

**Comment by tadpoleloop** [comment]
Oops, this message was meant for the connect4 solver and not this project.

**Comment by lhorrell99** [comment]
been a while! but I seem to remember this solve anything from about 12/13 moves in - any earlier in the game than that and it takes too long.

Haven't ever tried compiling as a Cython project - sounds like it could be well worth a try :)
